services:
  # Backend API Service
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add these lines to your dashboard for the actual values:
    # - key: EMAIL_USER
    #   value: your-email@gmail.com
    # - key: EMAIL_PASS
    #   value: your-app-password 