services:
  # Backend API Service
  - type: web
    name: portfolioDorDavid
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add these lines to your dashboard for the actual values:
    # - key: EMAIL_USER
    #   value: your-email@gmail.com
    # - key: EMAIL_PASS
    #   value: your-app-password 